### ISSUE TITLE
Can I show tags in the currently open file only?

### ISSUE THREAD

**Issue by marlun** [tsukkee/unite-tag#21]
In FuzzyFinder I use :FufBufferTag to show tags in the currently open file only, is that possible with unite-tag?

**Comment by euoia** [comment]
@Shougo unite-outline seems to be unmaintained. The last commit was on Feb 21, 2012 and when I try to use it with a new version of unite I get an error about g:unite_abbr_highlight being undefined.

**Comment by euoia** [comment]
Ah, just found https://github.com/Shougo/unite-outline.

**Comment by Shougo** [comment]
> @Shougo unite-outline seems to be unmaintained. The last commit was on Feb 21, 2012 and when I try to use it with a new version of unite I get an error about g:unite_abbr_highlight being undefined.

Yes.  Original unite-outline is not maintained.  I cannot contact with the author.

> Ah, just found https://github.com/Shougo/unite-outline.

It is my maintained version.
