### ISSUE TITLE
Support for alternative tags specification

### ISSUE THREAD

**Issue by DXist** [tsukkee/unite-tag#24]
It would be nice to add support for alternative tags list specification.

Use case:
* use default `tags` option for navigation between project and its dependencies by tag under cursor
* use tags generated only from project files for unite candidates

**Comment by romgrk** [comment]
Duplicate: `coffescript` isnt supported by ctags but there is a `coffeetags` tool that can generate them. However, Unite-tag doesn't have a per-filetype setting for generating tags. 
Therefore, I have a `tags` file full of tags waiting for me that I cannot `Unite`.

I would say that having either that or https://github.com/tsukkee/unite-tag/issues/34 this would be ok. None is bad.

**Comment by Shougo** [comment]
https://github.com/Shougo/unite-outline/issues/64

Hmmm...
Same problem is in unite-outline.

**Comment by Shougo** [comment]
@romgrk unite-tag does not generate/use ctags command.
It just parses tags file.
What is the problem?
unite-tags is not automatically tag generation tool.

**Comment by Shougo** [comment]
> use tags generated only from project files for unite candidates

You can use tag/include source.
