### ISSUE TITLE
Support for multiple files with same tag

### ISSUE THREAD

**Issue by yannack** [tsukkee/unite-tag#27]
I have the same tag repeated multiple times, and this plugin only shows one of occurences.

    load_one_ballot	hardware/abstract_scanner.py	/^    def load_one_ballot(self, ballot):$/;"	m	class:AbstractScanner
    load_one_ballot	hardware/mock_scanner.py	/^    def load_one_ballot(self, ballot):$/;"	m	class:MockEpson
    load_one_ballot	hardware/network_scanner.py	/^    def load_one_ballot(self, ballot):$/;"	m	class:NetworkScanner

When I run :Unite tag and filter for load_one_ballot I only get the first occurence. Would it be possible to show all of the occurences ? Thanks

**Comment by Shougo** [comment]
I cannot reproduce the problem.
Multiple items are shown.

![Uploading snap.png . . .]()


You must upload minimal .vimrc and reproduce ways from Vim starting.

**Comment by yannack** [comment]
Use this as .vimrc : 

```
set nocompatible
filetype off                   " required for Vundle

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'gmarik/Vundle.vim'
Plugin 'Shougo/unite.vim'
Plugin 'tsukkee/unite-tag'
call vundle#end()

call unite#filters#matcher_default#use(['matcher_fuzzy'])
nnoremap <leader>t :Unite -start-insert -no-split tag<CR>
```
Run :PluginInstall

Then place this in /tmp/tags:
```
!_TAG_FILE_FORMAT	2	/extended format; --format=1 will not append ;" to lines/
!_TAG_FILE_SORTED	2	/0=unsorted, 1=sorted, 2=foldcase/
!_TAG_PROGRAM_AUTHOR	Darren Hiebert	/dhiebert@users.sourceforge.net/
!_TAG_PROGRAM_NAME	Exuberant Ctags	//
!_TAG_PROGRAM_URL	http://ctags.sourceforge.net	/official site/
!_TAG_PROGRAM_VERSION	5.9~svn20110310	//
load_one_ballot	hardware/abstract_scanner.py	/^    def load_one_ballot(self, ballot):$/;"	m	class:AbstractScanner
load_one_ballot	hardware/mock_scanner.py	/^    def load_one_ballot(self, ballot):$/;"	m	class:MockEpson
load_one_ballot	hardware/network_scanner.py	/^    def load_one_ballot(self, ballot):$/;"	m	class:NetworkScanner
```

finally:

```
mkdir /tmp/test
cp /tmp/tags/ /tmp/test/tags
cd /tmp/test
vi
<leader>t
==> observe: only one candidate for load_one_ballot instead of expected 3 candidates
```

**Comment by yannack** [comment]
Were you able to reproduce ?

**Comment by Shougo** [comment]
I get it.
Please increase `g:unite_source_tag_max_fname_length` value like this:

```vim
set nocompatible

set runtimepath+=~/work/unite.vim
set runtimepath+=~/work/unite-tag/

let g:unite_source_tag_max_fname_length = 50

call unite#filters#matcher_default#use(['matcher_fuzzy'])
nnoremap ,t :Unite -start-insert -no-split tag<CR>
```

**Comment by yannack** [comment]
This does *not* fix the issue for the tags I sent as an example. For me the issue is still present using the example I sent and your .vimrc. A quick note: to use the actual tags I pasted, you need to have tabs instead of spaces (the markdown lost the tabulations), as such:
```
load_one_ballot<TAB>hardware/abstract_scanner.py<TAB>/^    def load_one_ballot(self, ballot):$/;"<TAB>m<TAB>class:AbstractScanner
```

**Comment by Shougo** [comment]
Please clear unite-tag's cache manually.

https://github.com/tsukkee/unite-tag/issues/28

**Comment by yannack** [comment]
Indeed, now it works ! Thanks !
