### ISSUE TITLE
file name length

### ISSUE THREAD

**Issue by craescu** [tsukkee/unite-tag#28]
`let g:unite_source_tag_max_fname_length = 64`

This seems to have no effect regarding file name length.

**Comment by Shougo** [comment]
Please upload example output.

**Comment by craescu** [comment]
![unite-tag](https://cloud.githubusercontent.com/assets/941660/7000537/6dc79378-dc2e-11e4-92d4-c6f20f32e2d8.png)

Even in my .vimrc I have:
let g:unite_source_tag_max_fname_length = 64

**Comment by Shougo** [comment]
Please upload your minimal .vimrc.

**Comment by Shougo** [comment]
I get it.  The candidates are already cached.  So, `g:unite_source_tag_max_fname_length` is ignored.
Please remove unite cache file(`g:unite_data_directory`).

**Comment by craescu** [comment]
After removing ~/.cache/unite/tag it worked.
Thank you!
