### ISSUE TITLE
Add an option to specify max kind column width

### ISSUE THREAD

**Issue by Coacher** [tsukkee/unite-tag#32]
The same way it is done for `fname` and `relative_fname`. Right now `kind` maximum width is hardcoded to [10](https://github.com/tsukkee/unite-tag/blob/master/autoload/unite/sources/tag.vim#L331), which is a bit much if only shortened kind is shown.

Please add the similar `g:unite_source_tag_max_kind_length` option.

**Comment by Shougo** [comment]
Implemented.

**Comment by Coacher** [comment]
Thank you!
