### ISSUE TITLE
Tags Don't Show with tag/include When First Opened

### ISSUE THREAD

**Issue by austinwagner** [tsukkee/unite-tag#33]
When I open the Unite window with the tag/include source, if the source has not been used yet or neocomplete has not been invoked in the current buffer, the tag list is empty. Forcing a unite_redraw does not cause the results to show up but they will show if I close and reopen the Unite window.

**Comment by Shougo** [comment]
You should execute `NeoIncludeMakeCache` command before `:Unite tag/include`.
Because the file is not cached.
