### ISSUE TITLE
Add sorter with a first priority for the current file

### ISSUE THREAD

**Issue by WscriChy** [tsukkee/unite-tag#34]
Is it possible to sort tags with first priority for tags from the current file?

**Comment by Shougo** [comment]
If it is implemented.
Why do you need the feature?
The feature is really useful?

**Comment by wsdjeg** [comment]
people use tags most do not want to goto current file,if you want you can use `/` and `?`
i think tags file most be used to goto definition,
for example i add jdk src tags into vim ,then use this plugin to read src

**Comment by Shougo** [comment]
#35 is merged.  Closing.
