### ISSUE TITLE
open the file in the current buffer,cover my origin file,maybe it should save my file before.

### ISSUE THREAD

**Issue by wsdjeg** [tsukkee/unite-tag#36]
```vim 
    autocmd BufEnter *
                \   if empty(&buftype)
                \|      nnoremap <buffer> <C-]> :<C-u>UniteWithCursorWord -immediately tag<CR>
                \|  endif
```
here is my config for unite-tag,and my os is ubuntu ,gvim 7.4
then i open vim with a new file named Test.java type into
```java
class Test{
  String
}
```
and do not save it,my cursor in on `String` then i type c-]
the vim show me the resuly in the unite buffer,if i select one and type Enter,the file will be opened in the current buffer,and cover my new file without save it!
i think it is better to confirm whether the file in current buffer has been saved,if not open the selection in a split buffer.[nerdtree](https://github.com/scrooloose/nerdtree) also has this feature ,maybe you can have a try.

**Comment by Shougo** [comment]
It is not unite-tag issue.  It is unite.vim feature.

Is `hidden` option set?  If so, you can edit the buffer and save it.
I think it is no problem.

**Comment by wsdjeg** [comment]
ok let me read the unite's doc carefully
