### ISSUE TITLE
Auto Cache

### ISSUE THREAD

**Issue by ricardoseriani** [tsukkee/unite-tag#39]
Hi,

There is any way that I can auto-cache the tags file as soon as vim is opened ?

Thanks in advance

PS: Thanks for this very useful plugin

**Comment by Shougo** [comment]
Nothing.  I think it is not unite-tag work.
But you can use `neoinclude.vim` for it.

https://github.com/Shougo/neoinclude.vim

**Comment by ricardoseriani** [comment]
Humm...

I took a look in neoinclude.vim, but I can't find anything explaining why is that for.
Can you explain me, please ?

**Comment by Shougo** [comment]
I have not much time to explain it.
I'm too busy!
Hint:  You can use `:Unite tag/include`
