### ISSUE TITLE
Cursor jumps away from a definition after untoggling tag/include split

### ISSUE THREAD

**Issue by Coacher** [tsukkee/unite-tag#41]
Hello.

I have this tag/include profile:

```
call unite#custom#profile('tagbar', 'context', {
    \ 'quit': 0,
    \ 'buffer_name': 'Tagbar',
    \ 'start_insert': 0,
    \ 'vertical': 1,
    \ 'direction': 'topleft',
    \ 'toggle': 1,
\})
```

I toggle tag/include split with this mapping:

```
nmap <silent> <F1> :Unite -profile-name=tagbar tag/include<CR>
```

Steps to reproduce the problem:
1. Open a file with some definitions that tag/include can understand.
2. Hit `<F1>`. A split with tag/include is now open and focused.
3. Select any definition, hit `<CR>`. Cursor jumps to the selected definition in the file.
4. Hit `<F1>` again to close the tag/include split.

Expected results:
Cursor stays on the definition.

Actual results:
Cursor jumps away from the definition and positioned where it was when tag/include split was opened.

Please fix.

**Comment by Shougo** [comment]
It is the toggle feature.  Please remove it.

``` vim
call unite#custom#profile('tagbar', 'context', {
    \ 'quit': 0,
    \ 'buffer_name': 'Tagbar',
    \ 'start_insert': 0,
    \ 'vertical': 1,
    \ 'direction': 'topleft',
\})
```

**Comment by Coacher** [comment]
Thanks @Shougo, but I want `<F1>` to work like toggle for tag/include split. With config you've suggested `<F1>` doesn't close tag/include split once it's opened.

**Comment by Shougo** [comment]
It is unite bug.
I have fixed.

**Comment by Coacher** [comment]
I can confirm it's fixed with the latest Unite update.
Thank you very much, @Shougo.
