### ISSUE TITLE
not working for javascript files

### ISSUE THREAD

**Issue by hatelove85911** [tsukkee/unite-tag#42]
It doesn't work for javascript files.

I installed [tagbar ](https://github.com/majutsushi/tagbar)and [jsctags](https://github.com/ramitos/jsctags), which works fine for generating tags for javascript files.

But I can't get any tags for javascript files when use unite-tag, I tried :Unite tag/include, but just an empty window is opened without any tag.

**Comment by Shougo** [comment]
To use `tag/include`, you must install `neoinclude` plugin.
https://github.com/Shougo/neoinclude.vim

If you want to use auto generated tags by tagbar and jsctags, you should use `:Unite tag`.

**Comment by hatelove85911** [comment]
I've installed neoinclude plugin, I've installed [jsctags](https://github.com/ramitos/jsctags), I have following configuration in my vimrc. 

```
let g:neoinclude#ctags_commands = {
    \ '_' : 'ctags',
    \ 'javascript' : 'jsctags'
    \ }

let g:neoinclude#ctags_arguments = {
    \ 'javascript' : '-f'
    \ }
```

But it still doesn't work: I tried 
1. Unite tag
2. Unite tag/include
3. Unite tag:%
4. Unite tag/include:%

What's the problem here?

**Comment by Shougo** [comment]
Please upload sample javascript file.
I will test it.

**Comment by Shougo** [comment]
Do you know unite-tag feature?
For `Unite tag`, you must specify 'tags' option.

For `Unite tag/include`, I will test it.

**Comment by hatelove85911** [comment]
Below is the source code of a example javascript file I'm testing against:

```
var a = 1
var def = function () {

  var k = 1
  var j = 2;

  function uiui() {

  }
}

```

**Comment by Shougo** [comment]
For `:Unite tag`:

It works.

```
$ jsctags test.js -f > jstags
$ vim test.js
:setlocal tags=./jstags
```

For `:Unite tag/include`:
I have fixed the problem in neoinclude.
Please update it.

**Comment by hatelove85911** [comment]
thanks! @Shougo .

I tried, it's able to generate tags for first time. 
But I'm facing some weird cache issues. I'm not able to refresh the tag buffer for new tags.
I pressed <c-l> to refresh, but nothing happens.

**Comment by Shougo** [comment]
`:NeoIncludeMakeCache`
